import { Country } from './country.model';
import { Company } from './company.model';
import { Department } from './department.model';
import { JobTitle } from './job-title.model';
import { JobPosition } from './job-position.model';

export class EmployeeWithNavigationProperties {
    employee: Employee;
    country: Country;
    company: Company;
    department: Department;
    jobTitle: JobTitle;
    jobPosition: JobPosition;
    employee1: Employee;
    appUser: AppUser;

    constructor(model?) {
        model = model || {};
        this.employee = model.employee || new Employee();
        this.country = model.country || new Country();
        this.company = model.company || new Company();
        this.department = model.department || new Department();
        this.jobTitle = model.jobTitle || new JobTitle();
        this.jobPosition = model.jobPosition || new JobPosition();
        this.employee1 = model.employee1 || new Employee();
        this.appUser = model.appUser || new AppUser();
    }
}

export class AppUser {
    email: string;
    name: string;
    phoneNumber: string;
    surname: string;
    userName: string;

    constructor(model?) {
        model = model || {};
        this.email = model.email || null;
        this.name = model.name || null;
        this.phoneNumber = model.phoneNumber || null;
        this.surname = model.surname || null;
        this.userName = model.userName || null;
    }
}

export class Employee {
    id: string;
    creationTime: Date;
    creatorId: string;
    lastModificationTime: string;
    lastModifierId: string;

    tenantId: string;
    firstName: string;
    middleName: string;
    lastName: string;
    fullName: string;
    photo: string;
    birthPlace: string;
    birthDate: string;
    gender: number;
    religion: number;
    marital: number;
    nationality: number;
    education: number;
    street: string;
    city: string;
    stateProvince: string;
    zipPostal: string;
    phone: string;
    fax: string;
    email: string;
    bankAccount: string;
    nik: string;
    npwp: string;
    address: string;
    userId: string;
    employeeNumber: string;
    employeeStatus: number;
    joinedDate: string;
    terminationDate: string;
    leaveDate: string;
    baseSalary: number;
    salary: number;
    ptkp: number;
    umk: number;
    countryId: string;
    companyId: string;
    departmentId: string;
    jobTitleId: string;
    jobPositionId: string;
    parentId: string;
    deviceId: string;
    userName: string;
    password: string;
    lat: string;
    lng: string;
    radius: number;
    isLocationLockAttendance: boolean;
    isSelfieAttendance: boolean;

    /**
     * 
     * @param model 
     */
    constructor(model?) {
        model = model || {};
        this.id = model.id || null;
        this.creationTime = model.creationTime || null;
        this.creatorId = model.creatorId || null;
        this.lastModificationTime = model.lastModificationTime || null;
        this.lastModifierId = model.lastModifierId || null;

        this.tenantId = model.tenantId || null;
        this.firstName = model.firstName || null;
        this.middleName = model.middleName || null;
        this.lastName = model.lastName || null;
        this.fullName = model.fullName || null;
        this.photo = model.photo || null;
        this.birthPlace = model.birthPlace || null;
        this.birthDate = model.birthDate || null;
        this.gender = model.gender || 0;
        this.religion = model.religion || 0;
        this.marital = model.marital || 0;
        this.nationality = model.nationality || 0;
        this.education = model.education || 0;
        this.street = model.street || null;
        this.city = model.city || null;
        this.stateProvince = model.stateProvince || null;
        this.zipPostal = model.zipPostal || null;
        this.phone = model.phone || null;
        this.fax = model.fax || null;
        this.email = model.email || null;
        this.bankAccount = model.bankAccount || null;
        this.nik = model.nik || null;
        this.npwp = model.npwp || null;
        this.address = model.address || null;
        this.userId = model.userId || null;
        this.employeeNumber = model.employeeNumber || null;
        this.employeeStatus = model.employeeStatus || 0;
        this.joinedDate = model.joinedDate || null;
        this.terminationDate = model.terminationDate || null;
        this.leaveDate = model.leaveDate || null;
        this.baseSalary = model.baseSallary || 0;
        this.salary = model.sallary || 0;
        this.ptkp = model.ptkp || 0;
        this.umk = model.umk || 0;
        this.countryId = model.countryId || null;
        this.companyId = model.companyId || null;
        this.departmentId = model.departmentId || null;
        this.jobTitleId = model.jobTitleId || null;
        this.jobPositionId = model.jobPositionId || null;
        this.parentId = model.parentId || null;
        this.deviceId = model.deviceId || null;
        this.userName = model.userName || null;
        this.password = model.password || null;

        this.lat = model.lat || null;
        this.lng = model.lng || null;
        this.radius = model.radius || 0;
        this.isLocationLockAttendance = model.isLocationLockAttendance || false;
        this.isSelfieAttendance = model.isSelfieAttendance || false;
    }
}

export class EmployeeInformationUpdate {
    id: string;
    tenantId: string;
    firstName: string;
    middleName: string;
    lastName: string;
    fullName: string;
    photo: string;
    birthPlace: string;
    birthDate: string;
    gender: number;
    religion: number;
    marital: number;
    nationality: number;
    education: number;
    street: string;
    city: string;
    stateProvince: string;
    zipPostal: string;
    phone: string;
    fax: string;
    email: string;
    bankAccount: string;
    nik: string;
    npwp: string;
    address: string;
    userId: string;
    employeeNumber: string;
    employeeStatus: number;
    changeType: number;
    isDisabled: boolean;
    joinedDate: string;
    terminationDate: string;
    leaveDate: string;
    ptkp: number;
    deviceId: string;
    parentId: string;
    bloodType: number;
    payGroup: number;
    marriageDate: string;
    degree: string;
    faculty: string;
    major: string;
    instituteName: string;
    graduationYear: string;
    GPA: string;
    employeeType: number;
    startDate: string;
    exitDate: string;
    exitReason: string;
    businessPhone: string;
    businessEmail: string;
    directorateId: string;
    divisionId: string;
    pointofHire: string;
    locationId: string;
    projectId: string;
    vesselId: string;
    leaveGradeId: string;
    payGradeId: string;
    bankId: string;
    contractStartDate: string;
    contractEndDate: string;
    familyCardNumber: string;
    bpjsKsNumber: string;
    bpjsFaskes: string;
    bpjsKsStatus: string;
    bpjsTkNumber: string;
    passportNumber: string;
    passportExpiredDate: string;
    district: string;
    subDistrict: string;
    domicileAddress: string;
    addressAccordingtoId: string;
    savingBookNumber: string;
    bankName: string;
    countryId: string;
    companyId: string;
    departmentId: string;
    jobTitleId: string;
    jobPositionId: string;
    lat: string;
    lng: string;
    radius: number;
    isLocationLockAttendance: boolean;
    isSelfieAttendance: boolean;

    constructor(model?) {
        model = model || {};
        this.id = model.id || null;
        this.tenantId = model.tenantId || null;
        this.firstName = model.firstName || null;
        this.middleName = model.middleName || null;
        this.lastName = model.lastName || null;
        this.fullName = model.fullName || null;
        this.photo = model.photo || null;
        this.birthPlace = model.birthPlace || null;
        this.birthDate = model.birthDate || null;
        this.gender = model.gender || 0;
        this.religion = model.religion || 0;
        this.marital = model.marital || 0;
        this.nationality = model.nationality || null;
        this.education = model.education || null;
        this.street = model.street || null;
        this.city = model.city || null;
        this.stateProvince = model.stateProvince || null;
        this.zipPostal = model.zipPostal || null;
        this.phone = model.phone || null;
        this.fax = model.fax || null;
        this.email = model.email || null;
        this.bankAccount = model.bankAccount || null;
        this.nik = model.nik || null;
        this.npwp = model.npwp || null;
        this.address = model.address || null;
        this.userId = model.userId || null;
        this.employeeNumber = model.employeeNumber || null;
        this.employeeStatus = model.employeeStatus || 0;
        this.changeType = model.changeType || 0;
        this.isDisabled = model.isDisabled || false;
        this.joinedDate = model.joinedDate || null;
        this.terminationDate = model.terminationDate || null;
        this.leaveDate = model.leaveDate || null;
        this.ptkp = model.ptkp || 0;
        this.deviceId = model.deviceId || null;
        this.parentId = model.parentId || null;
        this.bloodType = model.bloodType || 0;
        this.payGroup = model.payGroup || 0;
        this.marriageDate = model.marriageDate || null;
        this.degree = model.degree || null;
        this.faculty = model.faculty || null;
        this.major = model.major || null;
        this.instituteName = model.instituteName || null;
        this.graduationYear = model.graduationYear || null;
        this.GPA = model.GPA || null;
        this.employeeType = model.employeeType || 0;
        this.startDate = model.startDate || null;
        this.exitDate = model.exitDate || null;
        this.exitReason = model.exitReason || null;
        this.businessEmail = model.businessEmail || null;
        this.businessPhone = model.businessPhone || null;
        this.directorateId = model.directorateId || null;
        this.divisionId = model.divisionId || null;
        this.pointofHire = model.pointofHire || null;
        this.locationId = model.locationId || null;
        this.projectId = model.projectId || null;
        this.vesselId = model.vesselId || null;
        this.leaveGradeId = model.leaveGradeId || null;
        this.payGradeId = model.payGradeId || null;
        this.bankId = model.bankId || null;
        this.contractStartDate = model.contractStartDate || null;
        this.contractEndDate = model.contractEndDate || null;
        this.familyCardNumber = model.familyCardNumber || null;
        this.bpjsKsNumber = model.bpjsKsNumber || null;
        this.bpjsFaskes = model.bpjsFaskes || null;
        this.bpjsKsStatus = model.bpjsKsStatus || null;
        this.bpjsTkNumber = model.bpjsTkNumber || null;
        this.passportNumber = model.passportNumber || null;
        this.passportExpiredDate = model.passportExpiredDate || null;
        this.district = model.district || null;
        this.subDistrict = model.subDistrict || null;
        this.domicileAddress = model.domicileAddress || null;
        this.addressAccordingtoId = model.addressAccordingtoId || null;
        this.savingBookNumber = model.savingBookNumber || null;
        this.bankName = model.bankName || null;
        this.countryId = model.countryId || null;
        this.companyId = model.companyId || null;
        this.departmentId = model.departmentId || null;
        this.jobTitleId = model.jobTitleId || null;
        this.jobPositionId = model.jobPositionId || null;

        this.lat = model.lat || null;
        this.lng = model.lng || null;
        this.radius = model.radius || 0;
        this.isLocationLockAttendance = model.isLocationLockAttendance || false;
        this.isSelfieAttendance = model.isSelfieAttendance || false;
    }
}

export class EmployeeInformation {
    id: string;
    tenantId: string;
    firstName: string;
    middleName: string;
    lastName: string;
    fullName: string;
    photo: string;
    birthPlace: string;
    birthDate: string;
    gender: number;
    religion: number;
    marital: number;
    nationality: number;
    education: number;
    street: string;
    city: string;
    stateProvince: string;
    zipPostal: string;
    phone: string;
    fax: string;
    email: string;
    bankAccount: string;
    nik: string;
    npwp: string;
    address: string;
    userId: string;
    employeeNumber: string;
    employeeStatus: number;
    changeType: number;
    isDisabled: boolean;
    joinedDate: string;
    terminationDate: string;
    leaveDate: string;
    ptkp: number;
    deviceId: string;
    parentId: string;
    bloodType: number;
    payGroup: number;
    marriageDate: string;
    degree: string;
    faculty: string;
    major: string;
    instituteName: string;
    graduationYear: string;
    GPA: string;
    employeeType: number;
    startDate: string;
    exitDate: string;
    exitReason: string;
    businessPhone: string;
    businessEmail: string;
    directorateId: string;
    divisionId: string;
    pointofHire: string;
    locationId: string;
    projectId: string;
    vesselId: string;
    leaveGradeId: string;
    payGradeId: string;
    bankId: string;
    contractStartDate: string;
    contractEndDate: string;
    familyCardNumber: string;
    bpjsKsNumber: string;
    bpjsFaskes: string;
    bpjsKsStatus: string;
    bpjsTkNumber: string;
    passportNumber: string;
    passportExpiredDate: string;
    district: string;
    subDistrict: string;
    domicileAddress: string;
    addressAccordingtoId: string;
    savingBookNumber: string;
    bankName: string;

    countryId: string;
    companyId: string;
    departmentId: string;
    jobTitleId: string;
    jobPositionId: string;
    
    companyName: string;
    companyEmail: string;
    companyPhone: string;
    companyAddress: string;
    companyWebsite: string;
    departmentName: string;
    jobTitleName: string;
    jobPositionName: string;
    parentName: string;
    userName: string;
    isOvertime: boolean;
    lat: string;
    lng: string;
    radius: number;
    isLocationLockAttendance: boolean;
    isSelfieAttendance: boolean;

    constructor(model?) {
        model = model || {};
        this.id = model.id || null;
        this.tenantId = model.tenantId || null;
        this.firstName = model.firstName || null;
        this.middleName = model.middleName || null;
        this.lastName = model.lastName || null;
        this.fullName = model.fullName || null;
        this.photo = model.photo || null;
        this.birthPlace = model.birthPlace || null;
        this.birthDate = model.birthDate || null;
        this.gender = model.gender || 0;
        this.religion = model.religion || 0;
        this.marital = model.marital || 0;
        this.nationality = model.nationality || null;
        this.education = model.education || null;
        this.street = model.street || null;
        this.city = model.city || null;
        this.stateProvince = model.stateProvince || null;
        this.zipPostal = model.zipPostal || null;
        this.phone = model.phone || null;
        this.fax = model.fax || null;
        this.email = model.email || null;
        this.bankAccount = model.bankAccount || null;
        this.nik = model.nik || null;
        this.npwp = model.npwp || null;
        this.address = model.address || null;
        this.userId = model.userId || null;
        this.employeeNumber = model.employeeNumber || null;
        this.employeeStatus = model.employeeStatus || 0;
        this.changeType = model.changeType || 0;
        this.isDisabled = model.isDisabled || false;
        this.joinedDate = model.joinedDate || null;
        this.terminationDate = model.terminationDate || null;
        this.leaveDate = model.leaveDate || null;
        this.ptkp = model.ptkp || 0;
        this.deviceId = model.deviceId || null;
        this.parentId = model.parentId || null;
        this.bloodType = model.bloodType || 0;
        this.payGroup = model.payGroup || 0;
        this.marriageDate = model.marriageDate || null;
        this.degree = model.degree || null;
        this.faculty = model.faculty || null;
        this.major = model.major || null;
        this.instituteName = model.instituteName || null;
        this.graduationYear = model.graduationYear || null;
        this.GPA = model.GPA || null;
        this.employeeType = model.employeeType || 0;
        this.startDate = model.startDate || null;
        this.exitDate = model.exitDate || null;
        this.exitReason = model.exitReason || null;
        this.businessEmail = model.businessEmail || null;
        this.businessPhone = model.businessPhone || null;
        this.directorateId = model.directorateId || null;
        this.divisionId = model.divisionId || null;
        this.pointofHire = model.pointofHire || null;
        this.locationId = model.locationId || null;
        this.projectId = model.projectId || null;
        this.vesselId = model.vesselId || null;
        this.leaveGradeId = model.leaveGradeId || null;
        this.payGradeId = model.payGradeId || null;
        this.bankId = model.bankId || null;
        this.contractStartDate = model.contractStartDate || null;
        this.contractEndDate = model.contractEndDate || null;
        this.familyCardNumber = model.familyCardNumber || null;
        this.bpjsKsNumber = model.bpjsKsNumber || null;
        this.bpjsFaskes = model.bpjsFaskes || null;
        this.bpjsKsStatus = model.bpjsKsStatus || null;
        this.bpjsTkNumber = model.bpjsTkNumber || null;
        this.passportNumber = model.passportNumber || null;
        this.passportExpiredDate = model.passportExpiredDate || null;
        this.district = model.district || null;
        this.subDistrict = model.subDistrict || null;
        this.domicileAddress = model.domicileAddress || null;
        this.addressAccordingtoId = model.addressAccordingtoId || null;
        this.savingBookNumber = model.savingBookNumber || null;
        this.bankName = model.bankName || null;

        this.countryId = model.countryId || null;
        this.companyId = model.companyId || null;
        this.departmentId = model.departmentId || null;
        this.jobTitleId = model.jobTitleId || null;
        this.jobPositionId = model.jobPositionId || null;

        this.companyId = model.companyId || null;
        this.companyName = model.companyName || null;
        this.companyEmail = model.companyEmail || null;
        this.companyPhone = model.companyPhone || null;
        this.companyAddress = model.companyAddress || null;
        this.companyWebsite = model.companyWebsite || null;
        this.departmentName = model.departmentName || null;
        this.jobTitleName = model.jobTitleName || null;
        this.jobPositionName = model.jobPositionName || null;
        this.parentId = model.parentId || null;
        this.parentName = model.parentName || null;
        this.userName = model.userName || null;
        this.userId = model.userId || null;
        this.isOvertime = model.isOvertime || false;

        this.lat = model.lat || null;
        this.lng = model.lng || null;
        this.radius = model.radius || 0;
        this.isLocationLockAttendance = model.isLocationLockAttendance || false;
        this.isSelfieAttendance = model.isSelfieAttendance || false;
    }
}

export interface ImageSourceDto {
    id: string;
    fileContent: string;
  }