export* from './approval-status';
export* from './attendance-status';
export* from './DaysOfWeek';
export* from './education';
export* from './employee-status';
export* from './gender';
export* from './leave-detail-status';
export* from './leave-status';
export* from './leave-type';
export* from './marital';
export* from './nationality';
export* from './notification-type'
export* from './overtime-status';
export* from './overtime-type';
export* from './ptkp';
export* from './religion';
export* from './WorkDays';
export* from './relationship';
export* from './employee-change-type';